export const Constants = {
  REGISTER_EMAIL: 'trat@register.go.tz',
  FULL_BILL_PAY_TYPE: '1',
  SP_CODE: 'SP535',
  SYSTEM_ID: 'LTRAT001',
  JWT_SECRET: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
  JWT_REFRESH_TOKEN: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
  DB_HOST: 'localhost',
  API_KEY: 'jkiuyyayuu'
}